apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: parish-manager-ingress
spec:
  rules:
  - host: demo.servantscode.org 
    http: 
      paths:
      - path: /rest/person
        backend:
          serviceName: person-svc
          servicePort: 8080
      - path: /rest/family
        backend:
          serviceName: person-svc
          servicePort: 8080
      - path: /rest/login
        backend:
          serviceName: permission-svc
          servicePort: 8080
      - path: /rest/credential
        backend:
          serviceName: permission-svc
          servicePort: 8080
      - path: /rest/role
        backend:
          serviceName: permission-svc
          servicePort: 8080
      - path: /rest/permission
        backend:
          serviceName: permission-svc
          servicePort: 8080
      - path: /rest/ministry
        backend:
          serviceName: ministry-svc
          servicePort: 8080
      - path: /rest/enrollment
        backend:
          serviceName: ministry-svc
          servicePort: 8080
      - path: /rest/metrics
        backend:
          serviceName: metrics-svc
          servicePort: 8080
      - path: /rest/donation
        backend:
          serviceName: donation-svc
          servicePort: 8080
      - path: /rest/pledge
        backend:
          serviceName: donation-svc
          servicePort: 8080
      - path: /rest/event
        backend:
          serviceName: schedule-svc
          servicePort: 8080
      - path: /rest/reservation
        backend:
          serviceName: schedule-svc
          servicePort: 8080
      - path: /rest/room
        backend:
          serviceName: schedule-svc
          servicePort: 8080
      - path: /rest/equipment
        backend:
          serviceName: schedule-svc
          servicePort: 8080
      - path: /rest/photo
        backend:
          serviceName: photo-svc
          servicePort: 8080
      - path: /rest/note
        backend:
          serviceName: note-svc
          servicePort: 8080
      - path: /rest/email
        backend:
          serviceName: email-svc
          servicePort: 8080
      - path: /
        backend:
          serviceName: parish-manager
          servicePort: 80
