apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp1
  awsElasticBlockStore:
    volumeID: vol-0383e81b1daafe1d2
    fsType: ext4
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp1
